version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ruby:1.0
    container_name: sample.app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app