version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nuxt-dev:1.0
    container_name: sample.app
    working_dir: /app
    tty: true
    environment:
      HOST: '0.0.0.0'
      NODE_ENV: development
    command: bash -c "yarn install && yarn start -L"
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 3000:3000