version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: java:1.0
    container_name: java.app
    working_dir: /app
    tty: true
    command: bash -c "javac sample.java && java sample"
    volumes:
      - ./app:/app