version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cpp:1.0
    container_name: cpp.app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
    command: bash -c "./running.sh"