version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rust:1.0
    container_name: rust.app
    working_dir: /app
    tty: true
    command: bash -c "cargo run"
    volumes:
      - ./app:/app