version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: python:1.0
    container_name: python.app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app